apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: setup
  name: setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: setup
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/elk: "true"
        io.kompose.service: setup
    spec:
      containers:
        - env:
            - name: ELASTIC_PASSWORD
            - name: KIBANA_SYSTEM_PASSWORD
            - name: LOGSTASH_INTERNAL_PASSWORD
          image: setup
          name: setup
          resources: {}
          volumeMounts:
            - mountPath: /state
              name: setup
      restartPolicy: Always
      volumes:
        - name: setup
          persistentVolumeClaim:
            claimName: setup
status: {}
